//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesPropiedad
    {
        public int IdImagen { get; set; }
        public int IdPropiedad { get; set; }
        public string Src { get; set; }
        public bool Thumbnail { get; set; }
    
        public virtual Propiedades Propiedades { get; set; }
    }
}
