//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicaciones
    {
        public int IdPublicacion { get; set; }
        public int IdPropiedad { get; set; }
        public string Titulo { get; set; }
        public int IdOperacion { get; set; }
        public decimal Precio { get; set; }
        public string Moneda { get; set; }
        public bool Status { get; set; }
    
        public virtual Operaciones Operaciones { get; set; }
        public virtual Propiedades Propiedades { get; set; }
    }
}
