//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones
    {
        public int IdUbicacion { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public int IdMunicipio { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> IdPropiedad { get; set; }
    
        public virtual Municipios Municipios { get; set; }
        public virtual Propiedades Propiedades { get; set; }
    }
}
