//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ubicaciones()
        {
            this.Propiedades = new HashSet<Propiedades>();
        }
    
        public int IdUbicacion { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public int IdMunicipio { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    
        public virtual Municipios Municipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propiedades> Propiedades { get; set; }
    }
}
