//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caracteristicas()
        {
            this.CaracteristicasPropiedad = new HashSet<CaracteristicasPropiedad>();
        }
    
        public int IdCaracteristica { get; set; }
        public string Descripcion { get; set; }
        public bool Destacado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaracteristicasPropiedad> CaracteristicasPropiedad { get; set; }
    }
}
